version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambdas3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g7duuwb0ctb8"
s3_prefix = "lambdas3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FunctionName=\"DocumentDBRecipesFill\" LambdaLayerArn=\"arn:aws:lambda:us-east-1:706927318824:layer:pymongolayer:1\" InfraStackName=\"RecipesInfrastructure\" SecretManagerName=\"docdbrecipescreds\""
